theme: jekyll-theme-minimal
title: Jaehyun Han
logo: https://user-images.githubusercontent.com/45862440/157793704-7a918de7-e6ae-4d31-a11d-6dad3320a830.jpg
description: Data-driven analysis in international relations and security
show_downloads: false
google_analytics:
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji



