theme: jekyll-theme-minimal
title: Jaehyun Han 
description: *Data-driven analysis in interational relations and security*
View my professional profile [here](https://www.csis.org/people/jaehyun-han).

<img src = "https://user-images.githubusercontent.com/45862440/157776424-2d24a1ee-7ad4-48f8-a209-de2b8f916163.jpg" width = 25% height = 25%> <br/>
